src/main/kotlin/no/nav/syfo/infrastructure/cronjob/Cronjob.kt, src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobResult.kt, src/main/kotlin/no/nav/syfo/infrastructure/cronjob/JournalforForhandsvarselCronjob.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/DokarkivClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/AvsenderMottaker.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/Bruker.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/Dokument.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/DokumentInfo.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/Dokumentvariant.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/JournalpostRequest.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/JournalpostResponse.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/Sak.kt
- Legger til `dokarkiv` klient
- Legger til skjelett for cronjob for å gjøre journalføring av forhåndsvarsler
=> IS-2093: Add dokarkiv client + skeleton for journalforing of varsler

src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/infrastructure/ClientsEnvironment.kt, src/main/kotlin/no/nav/syfo/infrastructure/HttpClientCommon.kt, src/main/kotlin/no/nav/syfo/infrastructure/azuread/AzureAdClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/DokarkivClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdfgen/PdfGenClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/wellknown/WellKnownClient.kt
Disse brukes til å kalle tredjepart så virker mer logisk at de ligger der.
=> Flytter ClientsEnvironment og HttpClientCommon til infrastructure

src/main/kotlin/no/nav/syfo/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt, src/main/kotlin/no/nav/syfo/api/model/ForhandsvarselDTO.kt, src/main/kotlin/no/nav/syfo/domain/DocumentComponent.kt, src/main/kotlin/no/nav/syfo/infrastructure/veiledertilgang/VeilederTilgangskontrollPlugin.kt, src/test/kotlin/no/nav/syfo/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/UserConstants.kt, src/test/kotlin/no/nav/syfo/api/JWTUtil.kt, src/test/kotlin/no/nav/syfo/api/TestApiModule.kt, src/test/kotlin/no/nav/syfo/api/TestApplicationEngineUtils.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt, src/test/kotlin/no/nav/syfo/generator/DocumentComponentGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/AzureADMock.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/MockHttpClient.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/MockUtils.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/TilgangskontrollMock.kt, src/test/resources/jwkset.json
Satt opp API for forhåndsvarsel med tilhørende test. Det ble mye som måtte settes opp for å få testene opp og kjøre. Hvis dere vil at jeg skal flytte test-tingene ut i en egen PR så kan jeg også det 👍🏼
- Litt usikker på pakke-navn i `application`-laget, så kom gjerne med innspill på det!
- `ForhandsvarselDTO`, den er foreløpig lik som i `isaktivitetskrav`
=> IS-2092: Add endpoint for creating forhandsvarsel

src/main/kotlin/no/nav/syfo/application/IVarselPdfService.kt, src/main/kotlin/no/nav/syfo/application/IVurderingRepository.kt, src/main/kotlin/no/nav/syfo/application/service/ForhandsvarselService.kt, src/main/kotlin/no/nav/syfo/domain/Varsel.kt, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/VurderingRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdfgen/PdfGenClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdfgen/VarselPdfDTO.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdfgen/VarselPdfService.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/pdl/dto/PdlPersonResponse.kt, src/main/kotlin/no/nav/syfo/util/DateUtil.kt, src/test/kotlin/no/nav/syfo/application/service/ForhandsvarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/generator/VarselGenerator.kt, src/test/kotlin/no/nav/syfo/generator/VurderingGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt
Legger til service for å lagre forhåndsvarsel, og for å generere pdf.
Har ikke tatt i bruk i APIet enda, det blir en annen PR for å gjøre hver PR litt mindre 👍🏼
Tanker om test-oppsett? Jeg har mocket ut en del ting her, ønsker vi å gjøre det sånn for å teste servicen isolert, eller ønsker vi å teste mer integrasjoner? Hvis vi gjør det like isolert som her, så burde vi kanskje ha en egen test for pdf-gen også, når jeg tenker meg om 🤔
=> IS-2105: Add forhandsvarsel service

src/main/kotlin/no/nav/syfo/infrastructure/pdl/PdlClient.kt, src/test/kotlin/no/nav/syfo/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/UserConstants.kt, src/test/kotlin/no/nav/syfo/api/TestApiModule.kt, src/test/kotlin/no/nav/syfo/generator/PdlGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/MockHttpClient.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/PdfGenClientMock.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/PdlMock.kt, src/test/kotlin/no/nav/syfo/infrastructure/pdl/PdlClientSpek.kt
Se https://github.com/navikt/isarbeidsuforhet/pull/20 først.
For å få testet APIet gjennom hele løypa måtte vi ha på plass mocker for pdl og pdfgen.
La også inn en test for `pdlClient`.
=> IS-2105: Update mocks for pdl and pdfgen

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PVarsel.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PVarselPdf.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PVurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VarselRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/test/kotlin/no/nav/syfo/api/TestApiModule.kt, src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/TestDatabase.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt
Flytter disse til infrastructure.database.repository for å skille det fra database-config-filene.
=> Move P-classes and repositories to own package

.github/workflows/kafka-arbeidsuforhet.yaml, .nais/kafka/arbeidsuforhet-expired-varsel.yaml, .nais/kafka/dev.json, .nais/kafka/prod.json, src/main/kotlin/no/nav/syfo/infrastructure/kafka/ExpiredForhandsvarselProducer.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/ExpiredForhandsvarselRecordSerializer.kt, src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt
- Oppretter `teamsykefravr.arbeidsuforhet-expired-forhandsvarsel` topic
- Definerer første utgave av utgått varsel record som blir publisert på kafka. Utifra hva jeg kan se i `ispersonoppgave` for hvordan recorden til et utgått varsel for aktivitetskrav ser ut, så brukes bare `varselUuid`, `personIdent`, `varselType`. `varselType` stemmer jeg for at vi legger på om/når vi trenger det 😊 Bare å foreslå andre felter vi trenger, eventuelt felter vi ikke trenger.
=> IS-2094-3: Setup varsel expired topic, define record to publish

src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt
Fikk registrert duplikate forhåndsvarsel før i dag. Bør tilpasses på klientsiden også, men backend bør heller ikke tillate dette.
=> IS-2047: Ikke tillate duplikate FORHANDSVARSEL

src/main/kotlin/no/nav/syfo/infrastructure/kafka/VurderingProducer.kt
Unngår at vi wrapper value i et objekt og gjør det likt som andre kafka-dtoer.
=> Bruker String som type på personident på kafka-dto

src/main/kotlin/no/nav/syfo/api/model/VurderingResponseDTO.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt
Sånn at vi kan bruke dette til å vise fristen i frontend i stedet for å ha utregningen der også.
=> IS-2180: Add svarfrist to varsel response dto

src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt, src/main/kotlin/no/nav/syfo/api/model/VurderingRequestDTO.kt, src/main/kotlin/no/nav/syfo/application/IJournalforingService.kt, src/main/kotlin/no/nav/syfo/application/IVurderingPdfService.kt, src/main/kotlin/no/nav/syfo/application/IVurderingRepository.kt, src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/dokarkiv/dto/Dokument.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/dokarkiv/dto/JournalpostRequest.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/PdfGenClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/VurderingPdfService.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingService.kt, src/test/kotlin/no/nav/syfo/UserConstants.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt, src/test/kotlin/no/nav/syfo/application/service/ForhandsvarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt, src/test/kotlin/no/nav/syfo/generator/JournalpostRequestGenerator.kt, src/test/kotlin/no/nav/syfo/generator/VurderingGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/dokarkiv/DokarkivClientSpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingServiceSpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/DokarkivMock.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/PdfGenClientMock.kt
Se slacktråd for info om hvilke vurderinger som skal journalføres og ikke: https://nav-it.slack.com/archives/C06HMAY0ELA/p1709560585048279
Kort fortalt: `OPPFYLT` og `FORHANDSVARSEL` skal journalføres, ikke `AVSLAG`.
Logikken rundt journalføring er inspirert av https://github.com/navikt/isaktivitetskrav/blob/master/src/main/kotlin/no/nav/syfo/aktivitetskrav/domain/VarselType.kt#L13
Vi må etterhvert definere hvordan Oppfylt-dokumentet skal se ut i og oppdatere endepunkt i pdf-gen.
=> IS-2139: Add create-vurdering endpoint

src/main/kotlin/no/nav/syfo/application/IVarselProducer.kt, src/main/kotlin/no/nav/syfo/application/IVarselRepository.kt, src/main/kotlin/no/nav/syfo/application/service/VarselService.kt, src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/domain/JournalpostId.kt, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/infrastructure/cronjob/JournalforVurderingerCronjob.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PVurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VarselRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/VarselProducer.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/esyfovarsel/ArbeidstakerForhandsvarselProducer.kt, src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt, src/test/kotlin/no/nav/syfo/domain/JournalpostIdSpek.kt
Endrer slik at `sendArbeidstakerForhandsvarsel` tar inn `journalpostId` og `varsel` i stedet for vurdering.
Det er kun `journalpostId` vi egentlig bruker fra vurderingen, resten ligger på varsel. Tenker også det gir mer mening at en slik funksjon tar inn varsel.
Da trenger vi heller ikke respository-funksjon for å hente vurdering for et varsel.
Endrer også navn på cronjob siden vi skal journalføre mer enn forhåndsvarsel.
=> Refactor sendArbeidstakerForhandsvarsel and rename cronjob

src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VarselRepository.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VarselRepositorySpek.kt
- Legger til at man ikke publiserer utgått varsel om man har en vurdering `OPPFYLT` på samme person etter varselet har blitt laget.
- Her skulle vi hatt en test for å teste at man ikke henter ut varselet om det ligger en vurdering oppfylt, men finnes ikke funksjonalitet for dette enda.
=> IS-2155: Add varsel does not publish if oppfylt after varsel created

src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/PdfGenClient.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/VurderingPdfService.kt, src/test/kotlin/no/nav/syfo/UserConstants.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt, src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VarselRepositorySpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingServiceSpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/mock/PdfGenClientMock.kt
Etter litt diskusjon med Ingrid landet vi på at både OPPFYLG og AVSLAG skal journalføres, men ikke varsles eller vises til innbygger. Se https://nav-it.slack.com/archives/C06HMAY0ELA/p1710242102119539?thread_ts=1709560585.048279&cid=C06HMAY0ELA
=> IS-2139: Journalføre AVSLAG vurdering

src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt, src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/generator/VurderingGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VarselRepositorySpek.kt, src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt
For å bl.a. sørge for at Forhåndsvarsel-vurdering skal ha `varsel` og bare Avslag kan ha `gjelderFom`.
=> IS-2268: Implement Vurdering sealed interface

src/main/resources/db/migration/V1_6__update_vurdering_gjelder_fom.sql
Vi har ingen avslag-vurderinger i prod så dette er kun for at vi ikke skal få feil i dev når vi laster avslag-vurderinger som mangler gjelder_fom (https://github.com/navikt/isarbeidsuforhet/blob/main/src/main/kotlin/no/nav/syfo/domain/Vurdering.kt#L174)
=> IS-2268: Set gjelder_fom = created_at for avslag

src/main/kotlin/no/nav/syfo/application/IVurderingRepository.kt, src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt
Vi hadde en bug her som overskrev `journalpost_id` eller `published_at` når cronjobbene for å oppdatere disse skjedde på samme tid. Tilbakemeldingen fra datavarehus var at ting kom dobbelt på kafka, men det er jo mye mulig at noe har blitt journalført dobbelt også (men med ulike journalpostIDer).
=> IS-2350: Add separate update-functions for journalforing and published_at

.nais/kafka/arbeidsuforhet-vurdering.yaml, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/VurderingProducer.kt
Legger til boolsk `isFinalVurdering ` slik at konsument i `syfooversiktsrv` kan vite om vurderingen er endelig og at derfor arbeidsuforhet ikke lenger er relevant å vise for denne personen i oversikten.
- Se [tilhørende PR i syfooversiktsrv](https://github.com/navikt/syfooversiktsrv/pull/364)
=> IS-2271: Add isFinal values for VurderingType

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Legger til `syfooversiktsrv` til inbound access policy.
[Se relatert PR i syfooversiktsrv](https://github.com/navikt/syfooversiktsrv/pull/367)
=> IS-2271: Add syfooversiktsrv to inbound accesspolicy

src/main/kotlin/no/nav/syfo/domain/PersonIdent.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/ExpiredForhandsvarselProducer.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/VurderingProducer.kt
Kafka garanterer rekkefølgen innad i en partisjon og records med samme key vil havne på samme partisjon
=> Use personident-based record key to ensure order

src/main/resources/db/migration/V2_1__delete_wrong_varsel.sql
Sletter feilaktig sendt forhåndsvarsel
Ses i sammenheng med [denne](https://github.com/navikt/syfooversiktsrv/compare/IS-2824-delete-wrong-arbeidsuforhet-vurdering-set-to-inactive?expand=1)
=> IS-2824: Delete wrong forhandsvarsel

build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/IVurderingRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/KafkaConsumerService.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/KafkaConsumerTask.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/KafkaEnvironment.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/identhendelse/IdenthendelseConsumer.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/identhendelse/IdenthendelseKafkaTask.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/identhendelse/IdenthendelseService.kt, src/main/kotlin/no/nav/syfo/infrastructure/kafka/identhendelse/KafkaIdenthendelseDTO.kt, src/test/kotlin/no/nav/syfo/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/generator/IdenthendelseGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/identhendelse/IdenthendelseServiceSpek.kt
Leser inn alle identhendelser fra PDL og flytter vurderinger til ny (aktiv) ident der hvor det forekommer vurdering på inaktiv ident. Se for øvrig https://github.com/navikt/ishuskelapp/pull/110 for tilsvarende PR.
=> IS-3096: Handle identhendelser

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/IVurderingRepository.kt, src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/infrastructure/cronjob/RepublishForhandsvarselWithAdditionalInfoCronjob.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/test/kotlin/no/nav/syfo/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/generator/DocumentComponentGenerator.kt, src/test/kotlin/no/nav/syfo/infrastructure/cronjob/RepublishForhandsvarselWithAdditionalInfoCronjobSpek.kt
Hva gjør den:
- Gitt uuider (som vi må finne på forhånd og legge inn i lista)
- Finn nåværende vurderinger
- Kopier over all info, bortsett fra `svarfrist` og `document`
- Skriv over `document` med nye datoer (3 steder)
- Legger på en ekstratekst under overskriften og før første setning: `OBS! ...`
Hva gjenstår:
=> IS-3180: Create one-time job to generate new forhandsvarsler for non-notified varsler

src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/VurderingPdfService.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt, src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt, src/test/kotlin/no/nav/syfo/generator/VurderingGenerator.kt
Backend skal tillate registrering av avslag uten at det tidligere er gjort en forhåndsvarsling. Innfører egen vurderingstype for dette.
=> IS-2777: Avslag uten forhåndsvarsel

src/main/resources/db/migration/V2_6__add_column_vurdering_initiert_av.sql
- Legger til `vurdering_initiert_av` kolonne
Se [relatert PR](https://github.com/navikt/isarbeidsuforhet/pull/158) i `isarbeidsuforhet` som implementerer bruk av kolonnen
Ses i sammenheng med [denne PR'en](https://github.com/navikt/syfomodiaperson/pull/1731) i `syfomodiaperson`
=> IS-3337-2: Add vurdering_initiert_av column

src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt, src/main/kotlin/no/nav/syfo/api/model/VurderingRequestDTO.kt, src/main/kotlin/no/nav/syfo/api/model/VurderingResponseDTO.kt, src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt, src/main/kotlin/no/nav/syfo/domain/Vurdering.kt, src/main/kotlin/no/nav/syfo/domain/VurderingArsak.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PVurdering.kt, src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt, src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt, src/test/kotlin/no/nav/syfo/generator/VurderingGenerator.kt
- Legger til `vurderingInitiertAv` som en verdi som må være satt på en `AvslagUtenForhandsvarsel` vurdering.
Se [PR som legger til kolonne i db](https://github.com/navikt/isarbeidsuforhet/pull/159)
Se [PR som gjør nødvendige frontend endringer](https://github.com/navikt/syfomodiaperson/pull/1731)
=> IS-3337: Add initiertav to avslag uten forhandsvarsel vurdering
