navikt/isarbeidsuforhet

src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/DatabaseModule.kt

I stedet for å måtte spesifisere `ktor.environment` i `application.conf` prøver vi å hente `KTOR_ENV` fra nais-filene og bruker local som default value

Simplified isLocal check

---

src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
src/main/resources/db/migration/V1_1__create_user_cloudsqliamuser.sql
src/main/resources/db/migration/V1_2__create_user_isyfoanalyse.sql
src/main/resources/db/migration/V1_3__create_tables.sql

Forslag til databasetabeller. Brukt såpass generiske navn som Vurdering og Varsel foreløpig (så vi ikke låser oss helt til at det kun er forhåndsvarsel som kan journalføres og formidles til bruker i fremtiden)

IS-2089: Initial db tables

---

src/main/kotlin/no/nav/syfo/application/IVurderingRepository.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/PVarsel.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/PVarselPdf.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/PVurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/VurderingRepository.kt
src/test/kotlin/no/nav/syfo/UserConstants.kt
src/test/kotlin/no/nav/syfo/infrastructure/database/TestDatabase.kt
src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt

Implementert VurderingRepository for å lagre forhåndsvarsel-vurdering inkl varsel og pdf.

IS-2089: Repository for storing forhandsvarsel

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt
src/main/kotlin/no/nav/syfo/api/model/ForhandsvarselRequestDTO.kt
src/main/kotlin/no/nav/syfo/api/model/VurderingResponseDTO.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/VurderingRepository.kt
src/test/kotlin/no/nav/syfo/api/TestApiModule.kt
src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt
src/test/kotlin/no/nav/syfo/infrastructure/database/TestDatabase.kt

Se https://github.com/navikt/isarbeidsuforhet/pull/21 først.
Tar i bruk `forhandsvarselService` fra post-endepunktet, og returnerer `201` med `Varsel`-klassen.
Gjerne kom med kommentarer på TODOene og ellers hvordan vi vil at APIet skal oppføre seg 🙌🏼

IS-2105: Use forhandsvarselService from endpoint

---

src/main/kotlin/no/nav/syfo/application/service/VarselService.kt
src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/infrastructure/database/VurderingRepositorySpek.kt

Use repository with testdatabase in service-test

IS-2091: Improve test and fix bug

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/infrastructure/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/infrastructure/kafka/KafkaEnvironment.kt
src/test/kotlin/no/nav/syfo/TestEnvironment.kt

Trenger dette for å kunne sette opp en KafkaProducer til esyfovarsel-topic senere.

IS-2091: Add kafka environment and producer config

---

src/main/kotlin/no/nav/syfo/BackgroundTask.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobRunner.kt
src/main/kotlin/no/nav/syfo/infrastructure/leaderelection/LeaderPodClient.kt
src/main/kotlin/no/nav/syfo/infrastructure/leaderelection/LeaderPodDTO.kt

Dette er ting som må være på plass for å kjøre en cronjob, så tar det i en egen PR.
Gjerne kom med tilbakemeldinger på plassering av disse filene. `BackgroundTask` er feks i root, skulle den vært i feks `Util`-packagen?

IS-2115: Add setup for cronjob and leaderElection

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobModule.kt
src/test/kotlin/no/nav/syfo/TestEnvironment.kt

Kan testes i dev og merges etter https://github.com/navikt/esyfovarsel/pull/451 er merget

IS-2091: Setup running publish forhandsvarsel cronjob

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/IJournalforingService.kt
src/main/kotlin/no/nav/syfo/application/IVarselRepository.kt
src/main/kotlin/no/nav/syfo/application/service/VarselService.kt
src/main/kotlin/no/nav/syfo/domain/Varsel.kt
src/main/kotlin/no/nav/syfo/infrastructure/ClientsEnvironment.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobResult.kt
src/main/kotlin/no/nav/syfo/infrastructure/cronjob/JournalforForhandsvarselCronjob.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VarselRepository.kt
src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/Dokument.kt
src/main/kotlin/no/nav/syfo/infrastructure/dokarkiv/dto/JournalpostRequest.kt
src/main/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingService.kt
src/main/kotlin/no/nav/syfo/infrastructure/pdl/PdlClient.kt
src/test/kotlin/no/nav/syfo/ExternalMockEnvironment.kt
src/test/kotlin/no/nav/syfo/TestEnvironment.kt
src/test/kotlin/no/nav/syfo/UserConstants.kt
src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/generator/JournalpostRequestGenerator.kt
src/test/kotlin/no/nav/syfo/infrastructure/dokarkiv/DokarkivClientSpek.kt
src/test/kotlin/no/nav/syfo/infrastructure/mock/DokarkivMock.kt
src/test/kotlin/no/nav/syfo/infrastructure/mock/MockHttpClient.kt
src/test/kotlin/no/nav/syfo/infrastructure/mock/MockUtils.kt

Lagt inn cronjob og service for å journalføre. Se kommentarer i PR.
Har gitt oss tilgang til dokarkiv via https://github.com/navikt/dokarkiv/pull/578.

IS-2115: Add journalforing via cronjob

---

src/main/kotlin/no/nav/syfo/domain/Vurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/PdfGenClient.kt
src/main/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingService.kt
src/test/kotlin/no/nav/syfo/infrastructure/dokarkiv/DokarkivClientSpek.kt

Endrer fra "stans av" til "avslag på"
[Se tilhørende PR](https://github.com/navikt/isarbeidsuforhetpdfgen/pull/2) i `isarbeidsuforhetpdfgen`

IS-2133: Change from stans to avslag on forhandsvarsel

---

src/main/kotlin/no/nav/syfo/domain/Varsel.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/PVarsel.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VarselRepository.kt
src/main/kotlin/no/nav/syfo/infrastructure/database/repository/VurderingRepository.kt
src/main/kotlin/no/nav/syfo/infrastructure/kafka/ExpiredForhandsvarselProducer.kt
src/main/resources/db/migration/V1_6__alter_svarfrist_type_to_date.sql
src/test/kotlin/no/nav/syfo/application/service/VarselServiceSpek.kt
src/test/kotlin/no/nav/syfo/infrastructure/database/VarselRepositorySpek.kt

[Se bakgrunn for endring](https://github.com/navikt/isarbeidsuforhet/pull/34#discussion_r1509950011).
- Endrer dato type i database.
- Noen tanker om database migrering scriptet? 🙏 Lager en midlertidig `svarfrist_temp` for å holde eksisterende data slik at vi ikke trenger å bruke en kolonne med et annet navn selv om vi vil endre type.

IS-2149: Change from timestamp to date on svarfrist

---

src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt
src/main/kotlin/no/nav/syfo/domain/Vurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/VurderingPdfService.kt
src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt
src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt
src/test/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingServiceSpek.kt

Trenger litt tilbakemeldinger på hvordan vi ønsker å løse dette 👍🏼

IS-2218: Remove journalforing for AVSLAG and allow no begrunnelse and document in API

---

src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt

Vi ønsker å få live målinger i grafana, og setter opp metrics for vurderinger som blir gjort.

IS-2245: Add metrics for vurdering

---

src/main/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpoints.kt
src/main/kotlin/no/nav/syfo/api/model/VurderingResponseDTO.kt
src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt
src/main/kotlin/no/nav/syfo/domain/Varsel.kt
src/main/kotlin/no/nav/syfo/domain/Vurdering.kt
src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt
src/test/kotlin/no/nav/syfo/application/service/VurderingServiceSpek.kt
src/test/kotlin/no/nav/syfo/infrastructure/database/VarselRepositorySpek.kt

Laget også noen nye tester på valideringen og måtte oppdatere noen tester hvor vi bare laget avslag til å først lage et utløpt forhåndsvarsel (eller mocke det).

IS-2268: Add isExpired to varsel and dto. Check current vurdering is forhåndsvarsel on avslag.

---

.nais/kafka/arbeidsuforhet-vurdering.yaml

- Legger til at `syfooversiktsrv` har lesetilgang til topic `arbeidsuforhet-vurdering`

IS-2271: Add read access on topic to syfooversiktsrv

---

Dockerfile
build.gradle.kts

Oppdaterer til kotlin 2 og java 21

IS-2431: Update to kotlin 2.0 and jvm 21

---

.github/dependabot.yaml
README.md
build.gradle.kts

Sånn at dependabot finner avhengigheter og lagrer ukentige PRs på oppdateringer. Grupperer minor og patch-oppdatering i samme PR.

Fix dependabot

---

src/main/kotlin/no/nav/syfo/infrastructure/clients/dokarkiv/dto/JournalpostRequest.kt
src/main/kotlin/no/nav/syfo/infrastructure/journalforing/JournalforingService.kt
src/test/kotlin/no/nav/syfo/generator/JournalpostRequestGenerator.kt

For journalposter med type NOTAT skal det ikke settes avsender/mottaker: 
https://confluence.adeo.no/display/BOA/opprettJournalpost

IS-2670: Null ut mottaker for notat

---

src/main/resources/db/migration/V1_9__delete_wrong_varsel.sql

https://jira.adeo.no/browse/FAGSYSTEM-357811

IS-2822: delete wrong varsel

---

src/main/resources/db/migration/V2_2__trigger_revarsel_forhandsvarsel.sql

Kjøre varsling på nytt for utvalgte varsler fra uke 11
(forventer at 15 rader blir oppdatert)

IS-3178: Trigger revarsling forhandsvarsel

---

src/main/resources/db/migration/V2_3__delete_wrong_vurdering.sql

Se jira-sak https://jira.adeo.no/browse/FAGSYSTEM-380123

IS-3276: Delete wrong vurdering

---

src/main/resources/db/migration/V2_4__update_statistics.sql

Skal merges etter migrering til Postgres 17

IS-3251: Oppdaterer db-statistikk

---

src/main/kotlin/no/nav/syfo/application/service/VurderingService.kt
src/main/kotlin/no/nav/syfo/domain/Vurdering.kt
src/main/kotlin/no/nav/syfo/infrastructure/clients/pdfgen/VurderingPdfService.kt
src/test/kotlin/no/nav/syfo/api/endpoints/ArbeidsuforhetEndpointsSpek.kt
src/test/kotlin/no/nav/syfo/generator/VurderingGenerator.kt

Dette burde løse halvparten av problemet, kommer en egen PR med avslag uten forhåndsvarsel etterpå.

IS-2307: Oppfylt uten forhandsvarsel
